export enum Permission {
  USERS_READ = 'users.read',
  USERS_UPDATE = 'users.update',
  USERS_DELETE = 'users.delete',
  USERS_RESTORE = 'users.restore',
  LOGS_READ = 'logs.read',
  AUDITS_READ = 'audits.read',
  CATEGORY_READ = 'category.read',
  CATEGORY_CREATE = 'category.create',
  CATEGORY_UPDATE = 'category.update',
  CATEGORY_DELETE = 'category.delete',
  CATEGORY_RESTORE = 'category.restore',
  TRANSACTION_READ = 'transaction.read',
  TRANSACTION_CREATE = 'transaction.create',
  TRANSACTION_UPDATE = 'transaction.update',
  TRANSACTION_DELETE = 'transaction.delete',
  TRANSACTION_RESTORE = 'transaction.restore',
}
